export const FAMILY_VALUES = [
  "Adventure",
  "Education",
  "Creativity",
  "Nature & Outdoors",
  "Faith & Spirituality",
  "Health & Wellness",
  "Arts & Culture",
  "Community",
  "Quality Time",
  "Learning Through Play",
  "Environmental Awareness",
  "Cultural Diversity",
  "Family Traditions",
  "Physical Activity",
  "Kindness & Compassion",
  "Independence",
  "Teamwork",
  "Curiosity",
];

export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Chinese (Mandarin)",
  "Japanese",
  "Korean",
  "Arabic",
  "Hindi",
  "Russian",
  "Vietnamese",
  "Tagalog",
  "Polish",
  "Dutch",
  "Greek",
  "Hebrew",
  "Turkish",
  "Swedish",
];

export const FAMILY_ROLES = {
  adults: [
    "Mom",
    "Dad",
    "Grandma",
    "Grandpa",
    "Aunt",
    "Uncle",
    "Guardian",
    "Stepmom",
    "Stepdad",
    "Nanny",
  ],
  kids: [
    "Daughter",
    "Son",
    "Granddaughter",
    "Grandson",
    "Niece",
    "Nephew",
  ],
};

export const AGE_GROUPS = [
  "Infant (0-1)",
  "Toddler (1-3)",
  "Preschool (3-5)",
  "Elementary (5-12)",
  "Teen (13-17)",
  "Adult (18+)",
];
